export const userConstants = {

    FETCH_USERS_BEGIN: "FETCH_USERS_BEGIN",

    FETCH_USERS: "FETCH_USERS",

    SAVE_USER: "SAVE_USER",

    HANDLE_USER_ACTION_ERROR: "HANDLE_USER_ACTION_ERROR",
};

